development:
  cloud_name: drzbw0kaz
  api_key: '331565788819677'
  api_secret: 8Kei4uj58GqSxUzTS8l8slQ4jRQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drzbw0kaz
  api_key: '331565788819677'
  api_secret: 8Kei4uj58GqSxUzTS8l8slQ4jRQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drzbw0kaz
  api_key: '331565788819677'
  api_secret: 8Kei4uj58GqSxUzTS8l8slQ4jRQ
  enhance_image_tag: true
  static_image_support: false
